namespace CheersDb.Api.Dtos;

/// <summary>
/// Represents a standardized error response according to RFC 7807 (Problem Details for HTTP APIs).
/// </summary>
public class ProblemDetailsDto
{
	/// <summary>
	/// A URI reference [RFC3986] that identifies the problem type
	/// </summary>
	/// <example>https://cheersdb.org/error-codes/e100</example>
	public required string Type { get; init; }

	/// <summary>
	/// A short, human-readable summary of the problem type
	/// </summary>
	/// <example>Invalid request</example>
	public required string Title { get; init; }

	/// <summary>
	/// The HTTP status code ([RFC7231], Section 6) generated by the origin server for this occurrence of the problem
	/// </summary>
	/// <example>400</example>
	public required int Status { get; init; }

	/// <summary>
	/// A human-readable explanation specific to this occurrence of the problem
	/// </summary>
	/// <example>The request payload is missing the required 'username' field.</example>
	public required string Detail { get; init; }

	/// <summary>
	/// A URI reference [RFC3986] that identifies the specific occurrence of the problem
	/// </summary>
	/// <example>https://cheersdb.org/error-codes/e100/instances/12345</example>
	public string? Instance { get; set; }
}