name: PR Gatechecks

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    name: Build solution
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'

      - name: Restore
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore --configuration Release

      - name: Test
        run: echo ${{ env.GITHUB_WORKSPACE }}

      - name: OpenAPI Analyzer
        uses: ApyGuard/apyguard_openapi_analysis@v1.0.9
        with:
          file: ${{ env.GITHUB_WORKSPACE }}/src/CheersDb.Api/CheersDb.Api.json